# Generated by Django 4.1.2 on 2022-11-13 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='first',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('fname', models.CharField(max_length=50)),
                ('mail', models.CharField(max_length=40)),
                ('rollno', models.CharField(max_length=12)),
                ('mob', models.CharField(max_length=10)),
                ('branch', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('pass1', models.CharField(max_length=50)),
            ],
        ),
    ]
